.travis.yml
pom.xml
src/main/resources/bintray.json

This PR adds:
- SCM coordinates to be used with Maven Release Plugin
- configuration to upload files to bintray repository
Outline of release:
- push tagged version without `SNAPSHOT` suffix
- project.version == tag (e.g. `0.1`)
- this can be done manually (edit version, git tag, git push, update master to next iteration) or via release plugin `mvn prepare:release`
- upon successful new tag Travis job should do the heavy lifting of building and uploading to repository
- note that bintray.json descriptor is stored as a Maven resource to be build with proper project version

Road to automated release on tag push

---

src/main/java/cz/xtf/ssh/SshPrivateKeyNotFoundException.java
src/main/java/cz/xtf/ssh/SshUtil.java

In current implementation user needs to define ssh private key to be able to initialize Git repository. This is however not necessary as it should be possible to push to Git repo using username and password instead of key.
This change allows to initialize Git repo even when SSH private key is not defined.

Init Git repository when SSH private key not found

---

src/main/java/cz/xtf/TestConfiguration.java
src/main/java/cz/xtf/git/GitLabUtil.java

XTF expects the GitLab users to be in groups, failing operations for users without groups.
This PR allows to use users without groups.
By default user group support is enabled to keep backward compatibility.

Allow disabling support for GitLab user group

---

src/main/java/cz/xtf/openshift/OpenShiftUtil.java
src/test/java/cz/xtf/openshift/util/openshift/ImageStreamsTest.java

Since OpenShiftUtil can be simply instantiated it no longer needs namespace overriding methods. It's simpler for user to create new instance with working namespace then managing duplicate of all methods with namespace overriding.

Remove namespace overriding methods

---

src/main/java/cz/xtf/manipulation/ImageStreamProcessor.java

as that will cause creation of tags we don't wont (e.g. "latest")

Don't create dockerImageRepository entry for image streams

---

src/main/java/cz/xtf/openshift/OpenShiftUtil.java

Fixes update methods so they don't clean out untouched envs and create nonexisting and replace existing.

Fix update env vars methods

---

src/main/java/cz/xtf/openshift/OpenshiftApplication.java
src/main/java/cz/xtf/openshift/OpenshiftUtil.java
src/main/java/cz/xtf/openshift/builder/ApplicationBuilder.java
src/main/java/cz/xtf/openshift/builder/RoleBindingBuilder.java
src/main/java/cz/xtf/openshift/builder/RoleBuilder.java

While working on fix for https://issues.jboss.org/browse/CLOUD-2261 I would need to have chance to add roles and role binding as the image I use needs to list pods via api call.
Now I would like to add this ability to the xtf for me being able to use it then in xpaas qe test `test-eap/PostgreSQLXARecoveryLoadTest`. This is maintained by @tremes but I do some tweaks in it. I'm aware of the fact the changes goes to the deprecated part of the code (`OpenshiftUtil`) but the whole test is written in way of using it.
If you guide me how to do it in better way I will be more than happy.

[CLOUD-2261] adding roles builder as a way to define role when needed

---

src/main/java/cz/xtf/TestConfiguration.java
src/main/java/cz/xtf/XTFConfiguration.java

probably still not exactly what we want but at least make the envs make overwrite any previous ones so that our jenkins job can still function properly.
correct order is  test properties > system properties > env > global-test.properties > default
for images in TestConfiguration without this fix it is  
test properties > system properties >  global-test.properties  (with no way of using env)
this fix makes it
env >  test properties > system properties > global-test.properties 
which at least works with the jenkins job  (as we need env > global-test.properties at least)

quick fix for TestConfiguration env properties

---

src/main/java/cz/xtf/TestConfiguration.java

make sure the classes that use TestConfiguration use it in a way that calls the static initialization block

quickfix make sure we touch the static init block in TestConfiguration

---

utilities/src/main/java/cz/xtf/openshift/OpenshiftUtil.java

[utilities] use oc rollout instead of the deprecated oc deploy

---

utilities/src/main/java/cz/xtf/openshift/OpenshiftApplication.java

fixes a problem with two DCs with the same syncId, the wait did not actually wait for the second pod readiness at all.

[utilities] wait for specific DC during sync deployment

---

utilities/src/main/java/cz/xtf/XTFConfiguration.java
utilities/src/main/java/cz/xtf/build/BuildManagerV2.java
utilities/src/main/java/cz/xtf/manipulation/ProjectHandler.java
utilities/src/main/java/cz/xtf/openshift/OpenShiftUtil.java
utilities/src/main/java/cz/xtf/openshift/builder/secret/SecretType.java

Automatically create the pull secrets for an external openshift auth registry (e.g. registry.redhat.io) in the test and build-manager projects.

[utilities] secrets creation for registry.redhat.io

---

utilities/src/main/java/cz/xtf/openshift/ResourceParsers.java

There are two same classes:
./utilities/src/main/java/cz/xtf/openshift/ResourceParsers.java
./core/src/main/java/cz/xtf/core/openshift/helpers/ResourceParsers.java
This modification was introduced in core..helpers clone. I will create an issue (after some investigation) to unify this. https://github.com/xtf-cz/xtf/issues/157

[utilities] a pod can be ready only if it has at least one container

---

core/src/main/java/cz/xtf/core/image/Image.java
core/src/main/java/cz/xtf/core/image/UnknownImageException.java
pom.xml
product/pom.xml
product/src/main/java/cz/xtf/product/images/Images.java

Usage:
`xtf.product.image=registry.url/user/repo:tag` (optinal, used if specified)
`xtf.product.version1.image=ga.registry.url/user/repo:tag` (global.properties)
`xtf.product.version2.image=ga.registry.url/user/repo:tag` (global.properties)
`xtf.product.registry=customregistryid` (overrides used registry if not specified 'xtf.product.image')
`xtf.product.user=customuser` (overrides user if not specified 'xtf.product.image')
`xtf.product.tag=customtag` (overrides target tag if not specified 'xtf.product.image')
`xtf.registry.candidate=candidateregistry`
`xtf.registry.ga=garegistry`
`<profile>`
`	<id>version1</id>`
`	<properties>`
`		<xtf.eap.subid>version1</xtf.eap.subid>`
`	</properties>`
`</profile>`
`<profile>`
`<id>version2</id>`
`<properties>`
`<xtf.eap.subid>version2</xtf.eap.subid>` …

[product] Images

---

utilities/src/main/java/cz/xtf/TestConfiguration.java
utilities/src/main/java/cz/xtf/openshift/imagestream/ImageRegistry.java

Image contains oracle stuff in /extensions/. This enables template with external DB to include external driver thru EXTENSIONS_IMAGE.

[utilities] Added oracle extension image

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

binary build sometimes fails on connection timeouts. This should hopefully fix those.

[core] increase connection and build timeouts

---

builder/src/main/java/cz/xtf/builder/db/PostgreSQL.java
utilities/src/main/java/cz/xtf/openshift/db/PostgreSQL.java

Workaround for: https://github.com/sclorg/postgresql-container/issues/297
When OpenShift cluster is under higher load, and if PostgreSQL pod restart is requested (the pod is deleted & corresponding deployment config tries to deploy a new pod, for example like in the case of the _com.redhat.xpaas.sso.failover.DependencyFailoverTest.testDbPodRestart_ test), the new pod sometimes ends up / fails with the error message like the following (same like in the above GH issue):
```
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
........................................................... stopped waiting
server is still starting …
```

[KEYCLOAK-8742] [PostgreSQL.java] Default to PGCTLTIMEOUT equal to 300 seconds when creating PostgreSQL DB instances

---

builder/src/main/java/cz/xtf/builder/OpenShiftApplication.java
builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBindingBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBuilder.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
pom.xml
utilities/src/main/java/cz/xtf/openshift/OpenShiftUtil.java
utilities/src/main/java/cz/xtf/openshift/OpenshiftApplication.java
utilities/src/main/java/cz/xtf/openshift/OpenshiftUtil.java
utilities/src/main/java/cz/xtf/openshift/builder/ApplicationBuilder.java
utilities/src/main/java/cz/xtf/openshift/builder/RoleBindingBuilder.java
utilities/src/main/java/cz/xtf/openshift/builder/RoleBuilder.java

The changes will break the current API wherever `Role` and `RoleBinding` is used, but it should be easy enough to fix in affected code.

[core][utilities] upgrade openshift-client

---

builder/src/main/java/cz/xtf/builder/OpenShiftApplication.java
builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBindingBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBuilder.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
pom.xml
utilities/src/main/java/cz/xtf/openshift/OpenShiftUtil.java
utilities/src/main/java/cz/xtf/openshift/OpenshiftApplication.java
utilities/src/main/java/cz/xtf/openshift/OpenshiftUtil.java
utilities/src/main/java/cz/xtf/openshift/builder/ApplicationBuilder.java
utilities/src/main/java/cz/xtf/openshift/builder/RoleBindingBuilder.java
utilities/src/main/java/cz/xtf/openshift/builder/RoleBuilder.java

This reverts commit e5bd43391576dfdc3e5705c1f8da593d1c27af32.
Version `4.1.3` has broken `Endpoint` plural API. Should be fixed in the next.

Revert "[core][utilities] upgrade openshift-client"

---

builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
pom.xml

This PR adds a convenient method to pass client ref directly via `buildApplication()`.
```java
new OpenShiftApplication(applicationBuilder, openshift).deploy();
// is the same as
applicationBuilder.buildApplication(openshift).deploy();
```

[builder] add option to specify client in ApplicationBuilder

---

core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java
core/src/main/java/cz/xtf/core/openshift/OpenShifts.java

There is bug in openshift-client which does not allow currently to
connect with username to OCP 4.x https://github.com/fabric8io/kubernetes-client/issues/1505

Add way to use token instead of username/password for admin.

---

.gitignore
README.md
core/src/main/java/cz/xtf/core/config/XTFConfig.java

Added option to specify the `test.properties` and `global-test.properties` as a system property of `config.xtf.test.properties.path` and `config.xtf.global.test.properties.path`

Properties config feature

---

junit5/src/main/java/cz/xtf/junit5/extensions/SinceVersionCondition.java
junit5/src/main/java/cz/xtf/junit5/extensions/SkipForCondition.java
junit5/src/main/java/cz/xtf/junit5/listeners/ManagedBuildPrebuilder.java

Little performance enhancement which prevents unnecessary builds from being prepared for test classes that are skipped as a whole. Both `@SkipFor` and `@SinceVersion` are taken into consideration.

Don't prepare build for skipped test class

---

test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageContent.java

* Adding `Red Hat, Inc. (auxiliary key 2)` GPG key to `ImageContent` constants. This key is new backup key for RHEL8.
Please see [Product Signing Keys](https://access.redhat.com/security/team/key) for more information.

[Test Helpers, Image, RHEL8] Adding Red Hat, Inc. (auxiliary key 2) GPG key

---

builder/src/main/java/cz/xtf/builder/OpenShiftApplication.java
builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBindingBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBuilder.java
builder/src/main/java/cz/xtf/builder/builders/pod/ConfigMapVolume.java
core/src/main/java/cz/xtf/core/bm/BuildManager.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
pom.xml

Another take on client upgrade.
I wonder if we should implement some tests based on [mock servers](https://github.com/fabric8io/kubernetes-client/tree/master/openshift-server-mock/src/main/java/io/fabric8/openshift/client/server/mock) to be on a safe side. E.g. I haven't spotted any `Endpoints` tests even though the API was broken with double-plural issue in `v4.1.3`.

[all] upgrade openshift-client to v4.2.2

---

builder/src/main/java/cz/xtf/builder/OpenShiftApplication.java

In tests sometimes happens that deploy fails. This will provide additional information why it happened. 
For example in:
https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/OpenShift/job/eap-7.x-openshift-matrix-tests-72-matrix/47/CLUSTER_DOMAIN=multinode-nfs-005.dynamic.xpaas,label_exp=openshift-dynamic/testReport/com.redhat.xpaas.eap.hawkular/HawkularSecureConnectionTest/com_redhat_xpaas_eap_hawkular_HawkularSecureConnectionTest/
there was thrown exception after ~2 minutes but there was set 10 minutes timeout. I'm suspecting that there might be different reasons why deploy fails than just ```...Timeout while waiting for deployment of...```. If you want I can change message in exception as well to something like:
```Exception was thrown while waiting for deployment ...```

Log original exception when deployment fails

---

core/src/main/java/cz/xtf/core/bm/BinaryBuild.java

Without the update delete function just hangs forever.

Update delete for BinaryBuilds

---

core/src/main/java/cz/xtf/core/waiting/SimpleWaiter.java
core/src/main/java/cz/xtf/core/waiting/SupplierWaiter.java
core/src/main/java/cz/xtf/core/waiting/Waiter.java

Extends `Waiters` with reactive API that enables custom code hookup upon different situations that may come up during waiting (success, failure, timeout, customCondition).
Examples:
- `onFailure()` can print log of the pod to show the reason of unsuccessful start
- `reactOn()` will make handling issues like https://github.com/xtf-cz/xtf/pull/289 nicer

[core] Reactive waiters

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java
core/src/main/java/cz/xtf/core/openshift/crd/CustomResourceDefinitionContextProvider.java

A way to hook custom resources into `clean` method. Solution for #293 
`RoleBindings` and `Roles` owned by ClusterServiceVersion shouldn't be deleted as those are created by `OLM` and in case of their deletion a chaos may arise.

[core] Enable CRs clean up with clean

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

https://github.com/xtf-cz/xtf/issues/306
Use `withLabelNotIn` instead of `withoutLabel`.
```java
List<ConfigMap> configMapList = Stream.of(
new ConfigMapBuilder("keep-label-map").addLabel(KEEP_LABEL, null).build(),
new ConfigMapBuilder("null-label-map").build(),
new ConfigMapBuilder("arbitrary-label-map").build()
).collect(Collectors.toList());
openshift.configMaps().withoutLabel(KEEP_LABEL).list().getItems().size() == 3
openshift.configMaps().withLabel(KEEP_LABEL).list().getItems().size() == 1
openshift.configMaps().withLabelNotIn(KEEP_LABEL).list().getItems().size() = 2
```
Same goes also for other resources:
```java
openshift.pods().list().getItems().size() == 2
openshift.pods().withoutLabel(OpenShift.KEEP_LABEL).list().getItems().size() == 2 …
```

[core] [#306] Openshift.clean() doesn't take KEEP_LABEL into account

---

test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageContent.java

* Fixing ImageContent.listZipFilesInDir(String path) listing files in home directory besides zips in specified directory.

[testhelpers] ImageContent.listZipFilesInDir fix

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

https://github.com/xtf-cz/xtf/issues/308#issuecomment-537833455
What I am not sure is order of cleaning ReplicaSet. Does someone see problem with putting it in front to `Deployments`, `DeploymentConfigs`, `StatefulSets`, `ReplicationControllers`? I believe this object belongs to this set.
Running localy testsuite with this change in place.

[#308] Clean does not remove ReplicaSets

---

README.md
core/src/main/java/cz/xtf/core/bm/BuildManager.java
core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
junit5/README.md
junit5/src/main/java/cz/xtf/junit5/listeners/ProjectCreator.java

Resolves #283 
This PR adds support for pull secret in json format and mimics the openshift-install `pullSecret` parameter. It's quiet extensible to add additional registries e.g. quay, dockerhub there's no need to change the impl.
Please review and let me know if that's sufficient solution. I've tested it with in namespace deployment and with `BuildManager` successfully.
Format:
```json
{"auths":{"registry.redhat.io":{"auth":"<REDACTED_TOKEN>"}}}
```

Add OpenShift::setupPullSecret + config

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

continuing of https://github.com/xtf-cz/xtf/pull/146 , don't use `Collectors.toMap` in `getDeploymentConfigEnvVars` as that doesn't work with `null` values
ref: https://stackoverflow.com/a/24632080

[EnvVars] Avoid NPE in env vars when the value is null

---

pom.xml

I had the next issue when using this framework to connect with Openshift V4.3:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.xxxx/oapi/v1/namespaces/myproject/templates. Received status: Status(apiVersion=v1, code=404, details=null, kind=Status, message=null, metadata=null, reason=null, status=null, additionalProperties={}).
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:449)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372)
at …
```

Upgrade openshift-client to avoid issues with openshift 4

---

core/src/main/java/cz/xtf/core/openshift/OpenShifts.java

By default "master" user cannot read routes and cluster version, so "admin" user needs to be used. 
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.eapqe-004-wgcy.dynamic.xpaas:6443/apis/config.openshift.io/v1/clusterversions/version. Message: clusterversions.config.openshift.io "version" is forbidden: User "xpaasqe" cannot get resource "clusterversions" in API group "config.openshift.io" at the cluster scope.
```

read cluster version as admin

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java
core/src/main/java/cz/xtf/core/openshift/PodShell.java

When executing commands in pod, in case there are multiple containers in the pod, the execution fails with:
```
io.fabric8.kubernetes.client.KubernetesClientException: a container name must be specified for pod <pod>, choose one of: [<container1> <container2>]
at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.onFailure(ExecWebSocketListener.java:237)
at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:62 …
```

[PodShell] Add ability to execute cmd in pod with more containers

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java
junit5/src/main/java/cz/xtf/junit5/annotations/SinceVersion.java
junit5/src/main/java/cz/xtf/junit5/annotations/SkipFor.java
junit5/src/main/java/cz/xtf/junit5/extensions/SinceVersionCondition.java
junit5/src/main/java/cz/xtf/junit5/extensions/SkipForCondition.java
junit5/src/main/java/cz/xtf/junit5/model/DockerImageMetadata.java
test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageMetadata.java

**DockerImageMetadata**
- does not depend on jboss.dmr
- caches metadata for image streams
- checks for existing ones
- thread safe
- same api as ImageMetadata (means to replace it)
**SkipForCondition**
- uses DockerImageMetadata class
- gets name from metadata and applies the pattern
ImageMetadata class is deprecated now

Provide robust solution for recognizing image name for SkipFor logic

---

core/pom.xml
core/src/main/java/cz/xtf/core/event/EventList.java
core/src/main/java/cz/xtf/core/event/EventListFilter.java
core/src/main/java/cz/xtf/core/event/helpers/EventHelper.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
core/src/main/java/cz/xtf/core/waiting/SimpleWaiter.java
core/src/main/java/cz/xtf/core/waiting/SupplierWaiter.java
core/src/main/java/cz/xtf/core/waiting/Waiter.java
core/src/main/java/cz/xtf/core/waiting/helpers/ExponentialTimeBackoff.java
core/src/main/java/cz/xtf/core/waiting/helpers/FailFastBoolSupplierBuilder.java
core/src/test/java/cz/xtf/core/event/EventListTest.java
pom.xml

**EventList** and **EventListFilter**
- classes for storing and filtering events
**FailFastBoolSupplierBuilder**
- class for building bool supplier method that is used as function to check error state of cluster
- you can define which events show error state of cluster
**OpenShiftWaiters**
- added support for failfast approach
- defined waiters are with failfast function (empty by defeault) and returns false if failfast method returns true
@simkam @mnovak1 @LittleJohnII @mchoma 

Failfast support

---

core/src/main/java/cz/xtf/core/bm/BuildManager.java
core/src/main/java/cz/xtf/core/event/EventListFilter.java
core/src/main/java/cz/xtf/core/event/helpers/EventHelper.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
junit5/README.md
junit5/src/main/java/cz/xtf/junit5/annotations/OpenShiftRecorder.java
junit5/src/main/java/cz/xtf/junit5/config/JUnitConfig.java
junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderHandler.java
junit5/src/main/java/cz/xtf/junit5/extensions/helpers/ResourcesPrinterHelper.java
pom.xml

Add support to selectively save logs (pod logs, events,...) when a test throws an exception
You can specify resource names that will be considered (involved object names of events, names of pods,...).
It is turned into regular expression.

Record resources states when test throws an exception

---

junit5/src/main/java/cz/xtf/junit5/config/JUnitConfig.java
junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderHandler.java

Record openshift state even if beforeAll or beforeEach method fails.

Store openshift state if before* fails.

---

junit5/src/main/java/cz/xtf/junit5/extensions/helpers/ResourcesPrinterHelper.java

Change OpenshiftRecorder to print DockerImageRepository not PublicDockerImageRepository. PublicDockerImageRepository may not be present in imageStream, which causes the recorder to throw NPE and crash.

Print DockerImageRepository in openshift recorder.

---

junit5/src/main/java/cz/xtf/junit5/annotations/OpenShiftRecorder.java
junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderHandler.java
junit5/src/main/java/cz/xtf/junit5/extensions/helpers/EventsFilterBuilder.java
junit5/src/main/java/cz/xtf/junit5/extensions/helpers/ResourcesFilterBuilder.java
junit5/src/main/java/cz/xtf/junit5/extensions/helpers/ResourcesTimestampHelper.java

f not resource name is provided then filter resources automatically. A resource is logged if is created after a test starts (window for @BeforeAll is considered)

OpenShiftRecorder - automatic resource filtration

---

junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderHandler.java
junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderService.java

This is a refactoring of `OpenShiftrecorderHandler`.
We recently tried to use this handler logic directly inside one project which is consuming XTF, but two issues were found, see https://github.com/xtf-cz/xtf/issues/416 and https://github.com/xtf-cz/xtf/issues/417.
The class operational methods couldn't be overridden, since that part is private.
So this PR is based on @tommaso-borgato (thanks Tommaso) work to fix the above issues. Also the operational methods inside `OpenShiftRecorderService` class have been defined as `protected` so that a different (external) handler could have its own service that would extend it as needed.
Fix https://github.com/xtf-cz/xtf/issues/416
Fix https://github.com/xtf-cz/xtf/issues/417
- [**FAIL**] …

Refactoring OpenShiftRecorderHandler in order to split recording logic into a separate service

---

README.md
core/src/main/java/cz/xtf/core/bm/BuildManager.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
junit5/src/main/java/cz/xtf/junit5/listeners/ProjectCreator.java

Motivation for this is to have some common label for the projects/namespaces created by XTF automatically. This can ease their listing and tracing.
So far we search based on the 'openshift.io/requester' annotation value.

[feature] Label every created namespace.

---

README.md
test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageContent.java

As Maven 3.5 has reached EOL, RHEL will be moving to Maven 3.6. This will lead to change in the way Maven is added to the path. This PR adds a configuration `xtf.maven.activation_script` to allow to change maven activation script location. 
On systems where Maven activation script is not needed, the resulting script does not fail and correctly returns current Maven version.
Change is backwards compatible and defaults to current behaviour.
https://github.com/xtf-cz/xtf/issues/425
https://issues.redhat.com/browse/CLOUD-3955

Allow customization of maven activation script location

---

pom.xml

There is already LICENSE file (https://github.com/xtf-cz/xtf/blob/master/LICENSE). This is just mentioning it in the pom.xml to fullfill requirements for public Maven repos.

Provide link to MIT license used for XTF + other metadata about project

---

builder/src/main/java/cz/xtf/builder/db/AbstractSQLDatabase.java
builder/src/main/java/cz/xtf/builder/db/MySQL.java
builder/src/main/java/cz/xtf/builder/db/PostgreSQL.java
builder/src/main/java/cz/xtf/builder/db/ProbeSettings.java

Allow XTF library user to change probe settings by overriding `getProbeSettings` in his classes
Do not change behaviour and probe settings for Derby, MySQL, and PostgreSQL
What I did:
* Pulled duplicate code for liveness and readiness up into `AbstractSQLDatabase.java`
* Extracted MySQL and PostgreSQL probe settings from `configureContainer` to `ProbeSettings.java`
XTF library user will:
* derive his own class, for example `GalleonConfiguredDatasourcePostgreSQL extends PostgreSQL`
* optionally override `getProbeSettings`, using `super.getProbeSettings()` and updating them:
```java
public class GalleonConfiguredDatasourcePostgreSQL extends PostgreSQL {
// ...
@Override
protected ProbeSettings getProbeSettings() {
ProbeSettings settings = super.getProbeSettings(); …
```

Allow change to PostgreSQL and MySQL readiness and liveness probe settings

---

core/src/main/java/cz/xtf/core/config/WaitingConfig.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java

Using configuration values rather than some hardcoded timeouts in OpenShiftWaiters.
Fix https://github.com/xtf-cz/xtf/issues/438
FYI @mchoma

Replacing hardcoded 10 mins waiting with WaitingConfig.timeout for OpenShiftWaiters#hasBuildCompleted

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

as fabric8io/kubernetes-client#2373 was fixed, api version guessing can be streamlined.

Revert Fabric8 4.10 backward compatibility fix (#374) ad718b27

---

junit5/src/main/java/cz/xtf/junit5/listeners/TestExecutionLogger.java

to avoid races like
```
Aug 06, 2021 1:23:55 PM org.junit.platform.launcher.core.TestExecutionListenerRegistry lambda$notifyEach$1
WARNING: TestExecutionListener [cz.xtf.junit5.listeners.TestExecutionLogger] threw exception for method: executionFinished(TestIdentifier [uniqueId = '[engine:junit-jupiter]/[class:com.redhat.xpaas.eap.microprofile.health.MPHealthUpTest]/[method:healthCheckUpTest()]', parentId = '[engine:junit-jupiter]/[class:com.redhat.xpaas.eap.microprofile.health.MPHealthUpTest]', displayName = 'healthCheckUpTest()', legacyReportingName = 'healthCheckUpTest()', source = MethodSource [className = 'com.redhat.xpaas.eap.microprofile.health.MPHealthUpTest', methodName = 'healthCheckUpTest', methodParameterTypes = ''], tags = [level2, openshift-api], type = TEST], …
```

make TestExecutionLogger thread safe

---

core/src/main/java/cz/xtf/core/openshift/OpenShiftBinary.java

Common workflow is applying config files to setup pods. This PR aims to simplify applying (mutliple) config files.
Code snippet example now in use (we have some variations on this in EAP OpenShift testsuite)
```java
for (String yaml : Arrays.asList(
"bundle.yaml",
"prometheus-service-account.yaml",   
"prometheus-cluster-role.yaml", 
"prometheus-cluster-role-binding.yaml", 
"prometheus.yaml"
)) {
String absolutePath = String.format("%s/%s", tmpDir, yaml);
OpenShiftBinaryClient.getInstance().executeCommand("oc apply failed for : " + absolutePath,
"apply",
"-f",
absolutePath);
}
}
}
```
Could be simplified to
```java
List<String> absolutePaths = Stream.of(
"bundle.yaml", 
"prometheus-service-account.yaml",
"prometheus-cluster-role.yaml",  
"prometheus-cluster-role-binding.yaml", …
```

Simplify usage of `oc apply --filename=...`

---

core/src/main/java/cz/xtf/core/bm/BuildManager.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
junit5/src/main/java/cz/xtf/junit5/listeners/ProjectCreator.java
pom.xml

Although there are no API changes in XTF itself, it brings new kubernetes-client which contains many breaking changes. 
fixes #427 

bump openshift-client to 5.7.x

---

core/pom.xml
core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java
core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java
core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfoFactory.java
core/src/main/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolver.java
core/src/main/java/cz/xtf/core/openshift/ConfiguredPathOpenShiftBinaryResolver.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftBinaryManager.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftBinaryManagerFactory.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftBinaryPathResolver.java
core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
core/src/test/java/cz/xtf/core/openshift/ClusterVersionInfoTest.java
core/src/test/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolverTest.java
core/src/test/java/cz/xtf/core/openshift/ConfiguredPathOpenShiftBinaryResolverTest.java
core/src/test/java/cz/xtf/core/openshift/OpenShiftBinaryManagerFactoryTest.java
core/src/test/java/cz/xtf/core/openshift/OpenShiftsTest.java
core/src/test/resources/global-test.properties
pom.xml

fixes https://github.com/xtf-cz/xtf/issues/456
fixes https://github.com/xtf-cz/xtf/issues/462
- cache openshift version (loaded either from configuration or from cluster)
- download oc binary from
- mirror.openshift.com (if cluster version is known)
- cluster (if version is uknown assume OCP4 and download it from cluster)o
- binary download supports stable (default), latest, candidate and fast channels if configured version is in major.minor format only
Some public methods from `OpenShifts` class are marked as deprecated, they aren't now used internally by XTF and I believe they shouldn't have been public.
Some tests are included, the rest (major.minor only version, no version, no permissions to detect cluster version ...) tested manually.

[#456][#462] refactor logic determining cluster version and logic downloading oc binar

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java
pom.xml

https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md#590-2021-10-14
includes revert of workaround for an issue that was in 5.7.3 (fixes #461)
Results of our TS with this upgrade:
Failures are known or expected.

bump openshift-client to 5.9.0

---

core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
core/src/main/java/cz/xtf/core/openshift/PodShell.java
pom.xml

https://github.com/fabric8io/kubernetes-client/blob/v5.11.1/CHANGELOG.md
Results of our TS with this upgrade:
Failures are known or expected.
supersedes #468 

bump openshift-client to 5.11.1

---

junit5/pom.xml
junit5/src/main/java/cz/xtf/junit5/annotations/SkipFor.java
junit5/src/main/java/cz/xtf/junit5/extensions/SkipForCondition.java
junit5/src/test/java/cz/xtf/junit5/extensions/SkipForConditionTest.java

This PR is a proposal for adding support for skipping tests based on the `xtf.<productId>.subid` system property, as per the issue below, since WFLY 27 is not so far away...
Tests added as well, using https://mvnrepository.com/artifact/uk.org.webcompere/system-stubs-jupiter/2.0.1 which seems lightweight enough for use in test scope in order to set properties.
CC @mchoma
Fixes #470 

Adding support to skip tests based on provided xtf.<product ID>.subId

---

README.md
core/src/main/java/cz/xtf/core/service/logs/streaming/AnnotationBasedServiceLogsConfigurations.java
core/src/main/java/cz/xtf/core/service/logs/streaming/ServiceLogColor.java
core/src/main/java/cz/xtf/core/service/logs/streaming/ServiceLogColoredPrintStream.java
core/src/main/java/cz/xtf/core/service/logs/streaming/ServiceLogUtils.java
core/src/main/java/cz/xtf/core/service/logs/streaming/ServiceLogs.java
core/src/main/java/cz/xtf/core/service/logs/streaming/ServiceLogsSettings.java
core/src/main/java/cz/xtf/core/service/logs/streaming/ServiceLogsStreaming.java
core/src/main/java/cz/xtf/core/service/logs/streaming/SystemPropertyBasedServiceLogsConfigurations.java
core/src/main/java/cz/xtf/core/service/logs/streaming/k8s/PodLogs.java
core/src/main/java/cz/xtf/core/service/logs/streaming/k8s/PodLogsWatcher.java
core/src/test/java/cz/xtf/core/service/logs/streaming/AnnotationBasedServiceLogsConfigurationTest.java
core/src/test/java/cz/xtf/core/service/logs/streaming/ServiceLogColoredPrintStreamTest.java
core/src/test/java/cz/xtf/core/service/logs/streaming/ServiceLogsConfigurationTestHelper.java
core/src/test/java/cz/xtf/core/service/logs/streaming/SystemPropertyBasedServiceLogsConfigurationTest.java
junit5/README.md
junit5/src/main/java/cz/xtf/junit5/extensions/ServiceLogsStreamingRunner.java

Fix #474 
CC @mchoma, @simkam, @tommaso-borgato

Adding the Service Logs Streaming feature

---

junit5/src/test/java/cz/xtf/junit5/extensions/SkipForConditionTest.java

the main intention is to don't leak internal URL, but some checks were disabled because
- both metadata tests pass correctly only when valid kubeconfig is present locally
- they pass incorrectly without kubeconfig because tests ignore any other Exception message than is configured
- WildFly image doesn't have `architecture` label so it can't pass even with valid kubeconfig

change test image url and fail on any error in SkipForConditionTest

---

junit5/src/main/java/cz/xtf/junit5/model/DockerImageMetadata.java

The original implementation worked ok for one-part command list, eg:
```
"Cmd": [
"/opt/eap/bin/openshift-launch.sh"
],
```
But we can't expect all commands to be given like this, we need to be
able to parse also eg:
```
"Cmd": [
"sh",
"-c",
"${JBOSS_CONTAINER_WILDFLY_RUN_MODULE}/run"
],
```
This commits change the default behavior a bit (however, there is no change for those one-part commands) and adds new method to also be able to get command as list.

Provide the full command

---

junit5/pom.xml
junit5/src/main/java/cz/xtf/junit5/listeners/ManagedBuildPrebuilder.java
junit5/src/test/java/cz/xtf/junit5/extensions/SkipForConditionTest.java
junit5/src/test/java/cz/xtf/junit5/listeners/ManagedBuildPrebuilderTest.java

Before this PR, when class is annotated with `@SkipFor` or `@SinceVersion` and these annotations result in test class being skipped, we also skip pre-building of configured builds for that class (introduced in https://github.com/xtf-cz/xtf/pull/277).
This PR extends the check to also skip the build when test class is annotated with JUnit `@Disabled` annotation which further optimizes the execution.
Also some tests were added to verify the previous and enhanced behaviour.

Skip builds also for disabled test classes

---

builder/pom.xml
builder/src/test/java/cz/xtf/builder/openshift/mocked/smoke/BasicOpenShiftTest.java
pom.xml

Following up ion the discussion in https://github.com/xtf-cz/xtf/issues/325#issuecomment-1041556773, this (Draft) PR is a proposal for how to add some smoke tests that would check the components provided by XTF against a mocked OpenShift server.
The changes here are testing CRUD operations provided by the `OpenShift` class on a copule of resources, namely `ConfigMap` and `Deployment`, in order to prove the concept.
The PR itself could be extended conveniently.
@simkam, @mnovak1 WDYT? Could this way work for you as well?

Baseline for OpenShift tests using a mocked OpenShift server

---

junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderService.java

Adds the test method name to the generated directory name for parametrized tests, so that files can be downloaded without overriding existing ones.
FYI @mnovak1 (CC @simkam) - I am keeping this as a draft while I collect some runs to check the changes. Feel free to let me know what you think.
Fix #501 
Local execution with changes shows that now the test name is now used to compute the output directory name, so it will be unique for parametrized tests too:
```
ls -l junit5/
total 32
drwxrwxr-x. 2 fburzigo fburzigo 1024 Aug 29 13:41 cz.xtf.junit5.extensions.OpenShiftRecorderTest.failingParameterTest[2] 1
drwxrwxr-x. 2 fburzigo fburzigo 1024 Aug 29 13:41 cz.xtf.junit5.extensions.OpenShiftRecorderTest.failingParameterTest[3] 2
drwxrwxr-x. 2 fburzigo fburzigo 1024 Aug 29 13:42 …
```

Fix OpenShiftRecorderService in order to create a unique directory for parametrized tests

---

builder/src/main/java/cz/xtf/builder/builders/BuildConfigBuilder.java

fixes https://github.com/xtf-cz/xtf/issues/507
On OCP3 the property is ignored.

[#507] support mountTrustedCA in BuildConfigBuilder

---

core/src/main/java/cz/xtf/core/helm/HelmBinary.java
core/src/main/java/cz/xtf/core/openshift/CLIUtils.java

Helm v 3.10 adds support for `HELM_KUBEINSECURE_SKIP_TLS_VERIFY` environment variable (or `--kube-insecure-skip-tls-verify`) flag that doesn't require further kubecontext to be used in order for successful authentication. Such feature will be beneficial from testing POV. This PR addresses it.

Helm post 3.10 changes

---

core/src/main/java/cz/xtf/core/bm/BinaryBuildFromSources.java

In binary builds from sources, when the source is an already provisioned server (e.g. some "target/server" produced by the `wildfly-maven-plugin`), then execution permissions on ".sh" files are lost;
This causes the following error when the POD starts:
```
/opt/jboss/container/wildfly/run/run: line 74: /opt/server/bin/openshift-launch.sh: Permission denied
```
This MR just fixes permissions on ".sh" files which is the bare minimum required to have a working server installation;

Fixed permissions of shell scripts in binary builds

---

core/src/main/java/cz/xtf/core/namespace/NamespaceManager.java
junit5/src/main/java/cz/xtf/junit5/listeners/ProjectCreator.java

Namespace deletion between test cases causes intermittent issues. If namespace is created before it's actually deleted then creation of namespace looks like as namespace already exists and it's deleted a few seconds later causing unexpected issues. 
Unfortunately it looks like that kubernetes-client API does not provide reliable way to detect deleted namespace. Thus moving back to safe point and if `xtf.openshift.namespace.per.testcase=false` which is by default do not delete namespace. Only if `xtf.openshift.namespace.per.testcase=true` then delete namespace with nowait.
Also make deletion of namespace using `NamespaceManager.deleteProject(...)` more robust.

Fix namespace deletion

---

junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderService.java

I noticed this mismatch where all other save* calls differentiate filters for master and build namespace and only this one doesn't which is a bug introduced during refactoring and introducing this new `saveBuildLogs` method.

Use correct BUILD_FILTER_BUILDS filter for build namespace

---

builder/src/main/java/cz/xtf/builder/builders/pod/ContainerBuilder.java
builder/src/main/java/cz/xtf/builder/builders/pod/VolumeMount.java

This MR introduces the option to configure volumeMounts with subPath through cz.xtf.builder.builders.pod.ContainerBuilder

Configure VolumeMounts with subPath in ContainerBuilder

---

junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderService.java

Change OpenShiftRecorder to store logs from single Before* method failure into same directory. Currently it generates random integer, for directory name, every time writing a file. Resulting in storing every *.log file into separate directory.
This MR generates unique identifier every time a openshift state is stored and uses it as identifier for all files.
Changes behaviour from https://github.com/xtf-cz/xtf/pull/504

Record files from one Before* method failure to same directory

---

builder/src/main/java/cz/xtf/builder/builders/deployment/StartupProbe.java
builder/src/main/java/cz/xtf/builder/builders/pod/ContainerBuilder.java
builder/src/main/java/cz/xtf/builder/db/AbstractDatabase.java
builder/src/main/java/cz/xtf/builder/db/AbstractSQLDatabase.java
builder/src/main/java/cz/xtf/builder/db/MySQL.java
builder/src/main/java/cz/xtf/builder/db/PostgreSQL.java
builder/src/main/java/cz/xtf/builder/db/ProbeSettings.java

Adding startup probe functionality.
This code works as is, but if the startup probe fails tests still wait for a timeout. I propose also modifying waiter behavior to fail immediately if the startup probe is present and fails WDYT @mnovak1 ?
Resolves #520.

add startup probe

---

core/src/main/java/cz/xtf/core/bm/BinaryBuildFromSources.java

Due to big group ID number of the user the Apache compress throw exception when the user have big number as his group ID.  The big numbers can allowed by POSIX.

Configure Apache compress - use POSIX due to big group ID number of linux user

---

.github/workflows/pull-request-check.yml
pom.xml

impsort-maven-plugin requires JDK 11, old version that support JDK8 doesn't work with the latest maven
https://github.com/revelc/impsort-maven-plugin/issues/64

upgrade impsort-maven-plugin

---

pom.xml

plexus is no longer injected by maven
https://maven.apache.org/docs/3.9.1/release-notes.html
> Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer. See [MNG-6965](https://issues.apache.org/jira/browse/MNG-6965).

Fix impsort mvn 391

---

builder/src/main/java/cz/xtf/builder/builders/pod/ContainerBuilder.java

This MR fixed the `DeploymentConfig` produced by `ContainerBuilder`:
At present key and name are inverted:
```
- name: POSTGRESQL_ADMIN_PASSWORD
valueFrom:
configMapKeyRef:
name: postgresql-admin-password
key: postgresql
- name: POSTGRESQL_PASSWORD
valueFrom:
configMapKeyRef:
name: postgresql-password
key: postgresql
- name: POSTGRESQL_USER
valueFrom:
configMapKeyRef:
name: postgresql-user
key: postgresql
```
with this MR, the correct output is 
```
- name: POSTGRESQL_ADMIN_PASSWORD
valueFrom:
configMapKeyRef:
name: postgresql
key: postgresql-admin-password
- name: POSTGRESQL_PASSWORD
valueFrom:
configMapKeyRef:
name: postgresql
key: postgresql-password
- name: POSTGRESQL_USER
valueFrom:
configMapKeyRef:
name: postgresql
key: postgresql-user
```
Please make sure your PR meets the …

Fix configMapKeyRef: name and key are inverted

---

builder/src/main/java/cz/xtf/builder/builders/pod/ContainerBuilder.java

This MR add the option to use `secretKeyRef`, besides `configMapKeyRef`, in `DeploymentConfig` generated by `ContainerBuilder`, e.g.:
```
- name: KC_DB_USERNAME
valueFrom:
secretKeyRef:
name: postgresql
key: database-user
- name: KC_DB_PASSWORD
valueFrom:
secretKeyRef:
name: postgresql
key: database-password
```

Handle secretKeyRef in ContainerBuilder

---

core/pom.xml
core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java
core/src/main/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolver.java
core/src/test/java/cz/xtf/core/openshift/ClusterVersionInfoTest.java
core/src/test/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolverTest.java
pom.xml

fix ISE in cluster version detection

---

builder/src/main/java/cz/xtf/builder/builders/BuildConfigBuilder.java
builder/src/main/java/cz/xtf/builder/builders/ImageStreamBuilder.java
builder/src/main/java/cz/xtf/builder/builders/RoleBindingBuilder.java
builder/src/main/java/cz/xtf/builder/builders/buildconfig/SourceBuildStrategy.java
builder/src/main/java/cz/xtf/builder/builders/deployment/AbstractProbe.java
builder/src/main/java/cz/xtf/builder/builders/pod/ConfigMapVolume.java
builder/src/main/java/cz/xtf/builder/builders/pod/ContainerBuilder.java
builder/src/main/java/cz/xtf/builder/builders/pod/SecretVolume.java
core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java
core/src/main/java/cz/xtf/core/openshift/OpenShift.java
core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
junit5/src/main/java/cz/xtf/junit5/listeners/EventsRecorder.java
junit5/src/main/java/cz/xtf/junit5/model/DockerImageMetadata.java
pom.xml
test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageMetadata.java

Adding compatibility with Kubernetes Client 6.X.X.

Update Kubernetes Client to 6.X.X

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

Fixed null pointer reference when updating Deployment configs in javaopts tests. Same should apply to Buildconfigs.

Fix DeploymentConfig and BuildConfig update

---

core/src/main/java/cz/xtf/core/helm/ConfiguredVersionHelmBinaryPathResolver.java

When running tar in a docker container we face an issue https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233. Tar is used for unpacking the helm binary by the ConfiguredVersionHelmBinaryPathResolver.
7.4.x branch with the 0.30 SNAPSHOT test run https://cp-jenkins.eapqe.psi.redhat.com/job/eap-74x-openshift-4-xp4-openjdk11/125/.

Workaround for the issue when tar executed in docker container

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java

Fix getAnyPod throwing IllegalArgumentException when no pod with specified labels is found.
Now it throws an explained RuntimeException.

Fix getAnyPod throwing IllegalArgumentException when no pod found

---

builder/src/main/java/cz/xtf/builder/db/AbstractOracle.java
builder/src/main/java/cz/xtf/builder/db/OracleFREE.java
builder/src/main/java/cz/xtf/builder/db/OracleXE.java

Added Oracle FREE DB

---

builder/src/main/java/cz/xtf/builder/db/MsSQL.java

In the latest MSSQL Docker image (2022-latest refering to 2022-CU14-ubuntu-20.04) the path to sqlcmd was changed. This causes probe error during the start.
Tracked by [the mssql-docker issue](https://github.com/microsoft/mssql-docker/issues/892).
Related XTF issue https://github.com/xtf-cz/xtf/issues/573.

sqlcmd path updated for the newest MsSQL image

---

core/src/main/java/cz/xtf/core/image/Image.java
core/src/test/java/cz/xtf/core/image/ImageTest.java

CI runs: 
before: https://url.corp.redhat.com/06cd5f3
after: https://url.corp.redhat.com/4937bc9

[#571] Resolve image based on subid first.

---

core/src/main/java/cz/xtf/core/image/Image.java
core/src/test/java/cz/xtf/core/image/ImageTest.java

CI runs:  
Without fix: https://url.corp.redhat.com/a7db151
With fix: https://url.corp.redhat.com/bbed950
* GalleonDatasourceNoDriverVersionTest#noMsSQLDriverVersion,GalleonDatasourceFeaturePackMsSQLTest - caused by not updated mssql image
* Rerun HAServletCounterUpstreamKubePingTest,RollingUpdatesKubePingTest → https://url.corp.redhat.com/e8c1138 passed

[#572] Allow image url with more than 2 slashes to be parsed properly.

---

core/src/main/java/cz/xtf/core/openshift/CLIUtils.java

Extend the logging in case of failure to stdout as well. There are cases where this is useful.
I would like this to get to 0.34 (by releasing 0.35), but I guess this is applicable to any stream. Not urgent, no worries.
Please let me know if I've forgotten anything.

More logging in CLIUtils for better debugging

---

core/src/main/java/cz/xtf/core/openshift/CLIUtils.java

[#581] close Output and Error stream threads after command is done

---

core/pom.xml
core/src/main/java/cz/xtf/core/git/GitResolver.java
core/src/main/java/cz/xtf/core/git/GitResolverFactory.java
core/src/main/java/cz/xtf/core/git/GitUtils.java
core/src/main/java/cz/xtf/core/git/JGitResolver.java
core/src/main/java/cz/xtf/core/git/SystemPropertyGitResolver.java
pom.xml

Introduce `xtf.git.repository.url` and `xtf.git.repository.ref` properties intended for pointing to TS repo itself. 
This should get auto resolved via jgit, but can be overridden by manually setting properties
closes #574

implement jgit repository resolver

---

core/src/main/java/cz/xtf/core/image/Image.java
core/src/test/java/cz/xtf/core/image/ImageTest.java

Before this the returned URL was `quay.io/jaegertracing/all-in-one:1.56:`.

image URL without tag formatted by Image object shouldn't have trailing colon

---

builder/src/main/java/cz/xtf/builder/db/MySQL.java

Fix issues-588 by setting the correct MySQL Data Directory;
Now you can use both the following images by setting the correct `datadir`:
```
xtf.mysql.image=registry.redhat.io/rhel9/mysql-80:latest
xtf.mysql.datadir=/var/lib/mysql/data
```
or:
```
xtf.mysql.image=container-registry.oracle.com/mysql/community-server:8.0
xtf.mysql.datadir=/var/lib/mysql
```

Fix MySQL Data Directory

---

core/src/main/java/cz/xtf/core/openshift/OpenShift.java
test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageContent.java

Similary to https://github.com/xtf-cz/xtf/pull/280 addressing RHEL8 we would need provide update for RHEL9 as well.
In RHEL9 Red Hat, Inc. (auxiliary key 3) from https://access.redhat.com/security/team/key is used as backup key
CI runs are here [https://url.corp.redhat.com/066cc99](https://url.corp.redhat.com/066cc99)

[#599] Add RHEL9 Red Hat, Inc. (auxiliary key 3) GPG key

---

builder/src/main/java/cz/xtf/builder/db/AbstractDatabase.java
builder/src/main/java/cz/xtf/builder/db/AbstractSQLDatabase.java
builder/src/main/java/cz/xtf/builder/db/OfficialPostgreSQL.java
builder/src/main/java/cz/xtf/builder/db/PostgreSQL.java
builder/src/main/java/cz/xtf/builder/db/RedHatPostgreSQL.java

This PR:
- deprecates `PostgreSQL` builder for the postgres image which allows to differentiate images arguments and environment variables
- - adds `RedHatPostgreSQL` and `OfficialPostgreSQL` to handle respectively red hat Postgres image and the official Postgres image
- makes the necessary adaptations along the class hierarchy `PostgreSQL` -> `AbstractSQLDatabase` -> `AbstractDatabase` to propagate images arguments and environment variables and preserve default values

Add configuration options to PostgreSQL

---

README.md
RELEASE.md
pom.xml

Update distributionManagement values after Nexus 3 migration
