- src/main/java/cz/xtf/jolokia/JolokiaRequestBuilder.java
Operation execution takes precedence over the attribute read.
> Enhance JolokiaRequestBuilder to read attributes

- pom.xml
We need newer version of release plugin with fixed git scm library.
> Add release plugin version

- src/main/java/cz/xtf/openshift/OpenshiftUtil.java
this seems to help on OCP 3.7 ...
> update specific rolebindings object (by name)

- .travis.yml
- .travis/settings.xml
- pom.xml
This adds config of snapshot repo and Travis command to release from master.
> Snapshot release configuration

- src/main/java/cz/xtf/openshift/OpenshiftUtil.java
This method seems to get broken with fabric client version update
> Fix removeRoleFromEntity method

- utilities/src/main/java/cz/xtf/build/BuildManagerV2.java
- utilities/src/main/java/cz/xtf/build/PathBinaryBuildProcess.java
- utilities/src/main/java/cz/xtf/openshift/builder/ApplicationBuilder.java
- utilities/src/main/java/cz/xtf/openshift/builder/RouteBuilder.java
allows some testing on OSO starter
1. making the binary builds work
2. using default (no explicit hostname) on routes
3. making the applicationbuilder defaults aligned with OSO
> Enable some tests for OSO

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
Simple `PodPortForward` impl without `oc` binary.
> [core] add OpenShift::portForward method

- core/pom.xml
- http-client/pom.xml
- pom.xml
- test-helpers/pom.xml
- utilities/pom.xml
- Add version properties for jars
- Add version properties for plugins
- Add source plugin to attach sources upon release (IDE download sources functionality)
- Use common plugin configuration from parent pom
> Pom refactor & clean up

- pom.xml
Sorry, I've missed a few versions.
> [parent] fix missed version properties

- core/src/main/java/cz/xtf/core/openshift/helpers/ResourceParsers.java
a possible explanation for the "container not found" race
> [core] a pod can be ready only if it has at least one container

- utilities/src/main/java/cz/xtf/docker/DockerContainer.java
- utilities/src/main/java/cz/xtf/docker/OpenShiftNode.java
introducing OpenShiftNode.ofPod , move the ExternalIP hack to OpenShiftNode
> [utilities] OpenShiftNode.ofPod

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
- utilities/src/main/java/cz/xtf/openshift/OpenShiftUtil.java
@Crumby should I expand it all resources?
> [core] add delete filter for xtf.cz/keep labeled resources

- utilities/src/main/java/cz/xtf/openshift/messaging/AmqStandaloneBuilder.java
> [utilities] fix regression in AmqStandaloneBuilder

- utilities/src/main/java/cz/xtf/openshift/messaging/AmqStandaloneBuilder.java
> [utilities] fix withCustomBuild() in AmqStandaloneBuilder

- pom.xml
Might be worth to upgrade before major changes. No API changes this time.
> [all] upgrade openshift-client

- builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
or... I can just name all of them "get" ... whichever you prefer.
> [builder] fromImage, fromManagedBuild, fromS2IBuild

- core/src/main/java/cz/xtf/core/bm/BinaryBuild.java
- core/src/main/java/cz/xtf/core/bm/BinaryDockerBuild.java
- core/src/main/java/cz/xtf/core/bm/BinarySourceBuild.java
allow override of strategy  (to allow Docker strategy instead of Source)
> [core] ability to override strategy in BinaryBuild

- test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageMetadata.java
should fix occasional
java.lang.NullPointerException
at cz.xtf.testhelpers.image.ImageMetadata.prepare(ImageMetadata.java:42)
at cz.xtf.testhelpers.image.ImageMetadata.prepare(ImageMetadata.java:33)
> [test-helpers] use waiter instead of the hardcoded 10s wait

- core/src/main/java/cz/xtf/core/openshift/PodShell.java
- test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageContent.java
a few desperate attempts at fixing random failures at the beginning of tests using the ImageContent
should not hurt either way.
> Maschmid fixes

- core/src/main/java/cz/xtf/core/openshift/OpenShiftBinary.java
* `execute()` now returns String with standard output.
* Fixes `Corrupted STDOUT by directly writing to native stream in forked JVM`
> [core] return String and fix corrupted STDOUT

- builder/src/main/java/cz/xtf/builder/OpenShiftApplication.java
- builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
> [builder] deprecate opinionated OpenShiftApplication constructor

- builder/src/main/java/cz/xtf/builder/builders/PodBuilder.java
- builder/src/main/java/cz/xtf/builder/builders/pod/ConfigMapVolume.java
> Allow to set default mode for config map volume

- pom.xml
Updating Lombok version should fix failing travis job with Java 11.
> Update lombok version

- core/src/main/java/cz/xtf/core/openshift/OpenShiftBinary.java
- Log `oc` error message to console when command exits with non-zero code
- Remove placebo flush
> [core] Log error from oc client

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
Fix for the cleanup hack https://github.com/xtf-cz/xtf/pull/289
> [core] Actually use hacked waiter condition

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- pom.xml
> Improve OpenShift::clean reliability

- builder/src/main/java/cz/xtf/builder/db/AbstractDatabase.java
Changed access modifiers to `protected`
> Change access modifier to AbstractDatabase

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
This should be temporary to enable usage of `4.3.0` version until the following issues are fixed.
- https://github.com/fabric8io/kubernetes-client/issues/1673
- https://github.com/fabric8io/kubernetes-client/issues/1674
> [core] add a temp workaround for cascading issues

- builder/src/main/java/cz/xtf/builder/builders/deployment/LivenessProbe.java
- builder/src/main/java/cz/xtf/builder/builders/deployment/ReadinessProbe.java
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
> Add support for periodSeconds into liveness and readiness probes

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- pom.xml
I've removed the "hack" and leveraged new method to specify propagation policy. However, one drawback is that I haven't found a way to set both `gracePeriod` and `propagationPolicy`. So far I haven't spotted any issues though.
> Client upgrade + clean refactor

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
Issue #296: Problem when getting logs of a pod with many containers -
Suggestion for API improvement
> [core] Added support for multiple containers in a pod for logs

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
https://github.com/xtf-cz/xtf/issues/312
I run into several problems with this one
1) KubernetesClientException in case that CRD is not registered
2) KubernetesClientException in case that no CRD instances exists - this one could happen if CRD resources are not cleaned properly (e.g. due to finalizers), but the role-bindings and other service accounts are, at this point listing the resources throws KubernetesClientException
3) `customResource(crdContextProvider.getContext()).delete(getNamespace());` doesn't seem to block anymore (I would bet that it was before, but we're too close to freeze now, so I cannot investigate more now), thus we need to wait after deleting, otherwise TS could run into issues like:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST …
```
> [core] [#312] Relax CRD clean in case CRD is not installed

- core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
issue #305
Wait for latest build to exist
> [bug] Small correction on waitForBuildCompleted if buildconfig not yet existing 

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- pom.xml
Good old times are coming back...
> Refactor OpenShift:clean to delete resources via list

- pom.xml
> [parent] upgrade common-compress version

- core/src/main/java/cz/xtf/core/config/WaitingConfig.java
- core/src/main/java/cz/xtf/core/waiting/SimpleWaiter.java
- core/src/main/java/cz/xtf/core/waiting/SupplierWaiter.java
- core/src/main/java/cz/xtf/core/waiting/Waiter.java
- pom.xml
https://github.com/xtf-cz/xtf/issues/316
```
new SimpleWaiter(() -> isConditionMet(), "Wait for condition to be met.")
.interval(100L)
.level(Level.DEBUG)
.waitFor();
```
*Waiter constructors could be extended as well if desired.
> Extend the Waiter interface with a level() 

- core/src/main/java/cz/xtf/core/config/WaitingConfig.java
- core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
issue: https://github.com/xtf-cz/xtf/issues/328
> [#328] Make clean project timeout configurable

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
Get `routeSuffix` just once and avoid races when called multiple times. 
Fixing formatting of empty lines.
> Make Openshift.generateHostname() thread safe

- core/src/main/java/cz/xtf/core/waiting/SimpleWaiter.java
> Fix NPE in SimpleWaiter

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
Fixes https://github.com/xtf-cz/xtf/issues/373
> Fix for Fabric8 4.10.2 backward compatibility issue

- core/src/main/java/cz/xtf/core/bm/BinaryBuild.java
- core/src/main/java/cz/xtf/core/bm/BinaryBuildFromFile.java
- core/src/main/java/cz/xtf/core/bm/BinaryBuildFromSources.java
- core/src/main/java/cz/xtf/core/bm/BinaryDockerBuild.java
- core/src/main/java/cz/xtf/core/bm/BinarySourceBuild.java
> Refactor BinaryBuild architecture and add option to build from file

- junit5/src/main/java/cz/xtf/junit5/model/DockerImageMetadata.java
- test-helpers/src/main/java/cz/xtf/testhelpers/image/ImageMetadata.java
when pulling image - check for tag condition that indicate import failure
> FailFast for DockerImageMetadata class 

- builder/src/main/java/cz/xtf/builder/builders/ConfigMapWithPropertyFilesBuilder.java
> NPE in ConfigMapWithPropertyFilesBuilder

- builder/src/main/java/cz/xtf/builder/builders/AbstractBuilder.java
- builder/src/main/java/cz/xtf/builder/builders/ApplicationBuilder.java
> Add option to predefine custom labels into a Application

- junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderHandler.java
> OpenShiftRecorder log builds and image streams from both namespaces

- .github/workflows/pull-request-check.yml
Travis CI is not able to update PR status as it using legacy Gihub API which does no longer work. Unfortunately for some reason it's not possible to update. 
So instead of wasting time fixing, let's try github actions as is more mature way to do CI/CD.
> Add github actions as PR check

- core/src/main/java/cz/xtf/core/bm/BinaryBuildFromFileAsInputStream.java
> Added support for binary build from file as input stream

- RELEASE.md
> Add RELEASE.md - https://github.com/xtf-cz/xtf/issues/264

- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
> Update obtain token OCP4.6 compatible

- .github/workflows/pull-request-check.yml
> Fix typo in GH actions workflow

- CONTRIBUTING.md
> Add CONTRIBUTING.md - https://github.com/xtf-cz/xtf/issues/264

- core/src/main/java/cz/xtf/core/openshift/OpenShiftBinary.java
> extend ocConfigPath compatibility to OCP 4.7

- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
Fixes #406
Updates clean function of OpenShift.java class to be compatible with OCP4.7. Otherwise it gets stuck on attempt to remove `kube-root-ca.crt` file which is immediately recreated by OpenShift in every namespace.
> Do not attempt to delete kube-root-ca.crt config map

- junit5/src/main/java/cz/xtf/junit5/extensions/OpenShiftRecorderHandler.java
Fix issue that OpenshiftRecorder fails on NullPointerException when recording state and master and build namespace are same. Because build namespace filters are not initiated it will cause NPE when accessing them.
> Fix NPE when recording state of same master and build namespace.

- .github/workflows/pull-request-check.yml
> [ci] Fix a typo in the name of the PR check job.

- pom.xml
> Update Openshift client to 4.13.0

- pom.xml
changes are minimal https://github.com/fabric8io/kubernetes-client/compare/v4.13.0...v4.13.3
> upgrade openshift client 4.13.3

- core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java
- core/src/main/java/cz/xtf/core/config/XTFConfig.java
- core/src/main/java/cz/xtf/core/openshift/OpenShift.java
- core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
- core/src/main/java/cz/xtf/core/waiting/Waiter.java
- core/src/main/java/cz/xtf/core/waiting/failfast/EventFailFastCheckBuilder.java
- pom.xml
Public Maven repos require to have javadoc when releasing. So this is to fullfill requirements for new Maven release repo (https://github.com/xtf-cz/xtf/issues/423)
> Generate javadoc for XTF sources

- pom.xml
> Add maven-gpg-plugin and introduce release profile

- pom.xml
Having at least one dev is hard requirement for jboss.org maven repo.
> Add information about developer

- pom.xml
This solves https://github.com/xtf-cz/xtf/issues/423.
> Change distribution management to jboss-releases-repository

- .github/workflows/xtf-maven-release.yml
> Update GH Actions: Deploy snaphots to jboss-snaphots-repository

- core/src/main/java/cz/xtf/core/openshift/OpenShiftWaiters.java
> Fix time unit when using build timeout

- README.md
- RELEASE.md
Updating documentation in order to cover recent changes.
Fix https://github.com/xtf-cz/xtf/issues/440
- N/A - Code is formatted, imports ordered, code compiles and tests are passing
- N/A - Code is self-descriptive and/or documented
FYI @mnovak1, CC @mchoma
> Documentation: minor fixes/formatting and updates to reflect XTF Maven repos changes

- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
> make OpenShifts.getBinaryPath thread safe

- builder/pom.xml
- core/pom.xml
- http-client/pom.xml
- junit5/pom.xml
- pom.xml
- test-helpers/pom.xml
Reason for this is very simple - generic `parent` is not very
explanating when you are searching for appropriate project among of
your IDEA projects. Since there is planned a major version bump, I
thought that this may be a good time to propose such thing...
> [parent] Add prefix for the parent artifact ID.

- core/src/main/java/cz/xtf/core/config/OpenShiftConfig.java
- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
- core/src/test/java/cz/xtf/core/openshift/OpenShiftsTest.java
> Add feature cache oc binary in local folder.

- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
- core/src/test/java/cz/xtf/core/openshift/OpenShiftsTest.java
> Update cache folder url from b64 to md5

- core/src/main/java/cz/xtf/core/openshift/OpenShifts.java
> Download oc for alternative arch

- core/src/main/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolver.java
> [#472] Fix OCP 3.11 mirror download URL

- junit5/src/main/java/cz/xtf/junit5/annotations/SkipFor.java
- junit5/src/main/java/cz/xtf/junit5/extensions/SkipForCondition.java
Re: https://github.com/xtf-cz/xtf/issues/479
I would like to test this with the EAP OpenShift test suite as well.
> Add architecture label check for SkipFor

- builder/src/main/java/cz/xtf/builder/builders/deployment/ExecHandler.java
- builder/src/main/java/cz/xtf/builder/builders/deployment/Handler.java
- pom.xml
Results from our test suite, failures are either expected or intermittent.
> bump openshift-client to 5.12.1

- core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java
- core/src/main/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolver.java
- core/src/test/java/cz/xtf/core/openshift/ClusterVersionInfoTest.java
[issue 491](https://github.com/xtf-cz/xtf/issues/491) fix.
> fix OCP version recognition

- junit5/src/main/java/cz/xtf/junit5/listeners/ProjectCreator.java
- junit5/src/main/java/cz/xtf/junit5/model/DockerImageMetadata.java
> #488 Create namespace if not exists

- core/src/main/java/cz/xtf/core/config/XTFConfig.java
Refactor mainly to use the configuration in test scenarios (allow the tests to change configuration on the fly using system properties)
> Make XTF configuration reloadable

- core/pom.xml
- core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfoFactory.java
- core/src/main/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolver.java
- core/src/test/java/cz/xtf/core/openshift/ClusterVersionInfoTest.java
- core/src/test/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolverTest.java
- core/src/test/resources/global-test.properties
- junit5/pom.xml
- pom.xml
Use stable channel to download oc client if version not found
> [#495] Use stable channel if version not found

- pom.xml
> bump openshift-client to 5.12.2

- RELEASE.md
> Update steps for XTF release

- .github/workflows/codeql-analysis.yml
by default, the CodeQL job is not running any queries see https://github.com/wildfly-extras/sunstone/pull/152#issuecomment-1432864075.
> add codeQL queries

- core/src/main/java/cz/xtf/core/openshift/OpenShiftBinaryManager.java
> 0.29 fix smongiar

- builder/src/main/java/cz/xtf/builder/OpenShiftApplication.java
this PR resolves #337
It appears that no changes for `ManagedBuildPrebuilder` are necessary
> enable failFast for Openshift deploy

- pom.xml
> Downgrade impsort plugin to JDK 8 compatible version

- core/src/main/java/cz/xtf/core/openshift/CLIUtils.java
Running locally works as expected. I see lines like 
```
[2024-02-13 08:41:23,906] DEBUG- executing local command: podman push --tls-verify=false default-route-openshift-image-registry.apps..../mchoma/build-dockerfile-local
```
in log.
> [#557] Add some logging for better troubleshooting

- core/src/main/java/cz/xtf/core/helm/ConfiguredVersionHelmBinaryPathResolver.java
- core/src/main/java/cz/xtf/core/openshift/ClusterVersionOpenShiftBinaryPathResolver.java
- core/src/main/java/cz/xtf/core/utils/CoreUtils.java
> add arm64 helm client retrieval support

- core/src/main/java/cz/xtf/core/waiting/SimpleWaiter.java
Added JavaDoc to `cz.xtf.core.waiting.SimpleWaiter#SimpleWaite`
> Added javadoc to cz.xtf.core.waiting.SimpleWaiter

- junit5/src/main/java/cz/xtf/junit5/extensions/SkipForCondition.java
https://github.com/xtf-cz/xtf/issues/591
CI run:  eap-8.x-openshift-4-80-openjdk17/683/ + rerun eap-8.x-openshift-4-80-openjdk17/684/
> [#591] continue in test if skip condition cant be evaluated

- pom.xml
https://github.com/xtf-cz/xtf/issues/590
Before
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for XTF 0.36-SNAPSHOT:
[INFO] 
[INFO] XTF ................................................ SUCCESS [  0.357 s]
[INFO] XTF :: Core ........................................ FAILURE [  2.792 s]
[INFO] XTF :: Builder ..................................... SKIPPED
[INFO] XTF :: JUnit5 ...................................... SKIPPED
[INFO] XTF :: Http Client ................................. SKIPPED
[INFO] XTF :: Test Helpers ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] …
```
> [#590] Upgrade lombok to support JDK21

- core/src/main/java/cz/xtf/core/bm/BuildManager.java
- core/src/main/java/cz/xtf/core/config/BuildManagerConfig.java
> [#601] Enforce skipping rebuild of builds
